/*
 * ota_pubkey.h — ed25519 public key baked into the firmware image.
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerated by: tools/sign/generate_keys.py
 *
 * This file IS committed to the repo (the public key is, after all,
 * public). The matching private key lives in tools/sign/private.pem
 * which is .gitignore'd and chmod 600.
 *
 * Fingerprint (sha256(pubkey)[:8] in hex): b5cbb87cfc060987
 *
 * Generated on: 2026-05-22 17:45:37 UTC
 */

#ifndef DASHBOARD_SECURE_OTA_PUBKEY_H
#define DASHBOARD_SECURE_OTA_PUBKEY_H

#include <stdint.h>

static const uint8_t ota_pubkey[32] = {
    0xc9, 0x1c, 0xc0, 0x48, 0xc9, 0x58, 0x10, 0x5e,
    0x00, 0xdb, 0xab, 0x06, 0xd5, 0x1d, 0x3f, 0xa6,
    0x45, 0x8a, 0x22, 0x3a, 0xb0, 0xa1, 0xe3, 0xd0,
    0x2c, 0x75, 0x91, 0xf5, 0x7f, 0x16, 0xd7, 0x2c
};

#endif /* DASHBOARD_SECURE_OTA_PUBKEY_H */
