#!/usr/bin/env python3
"""
generate_keys.py — produce an ed25519 keypair for OTA signing.

Outputs:
  - tools/sign/private.pem        (PKCS8 PEM, chmodded 600 on POSIX)
  - main/secure/ota_pubkey.h      (C header with the 32-byte pubkey)

Usage:
  python tools/sign/generate_keys.py
  python tools/sign/generate_keys.py --force        # overwrite existing
  python tools/sign/generate_keys.py --out-dir X    # alternate dest

The header has the shape:

    static const uint8_t ota_pubkey[32] = { 0xAA, 0xBB, ... };

so a C source can `#include "ota_pubkey.h"` and use the constant
directly. The byte order is the raw RFC 8032 ed25519 public-key
encoding (32 bytes, no leading length, no ASN.1).

## Why

Bake-at-build keeps the trust anchor under our control: a baked key
cannot be tampered with at OTA time because the running firmware
contains it. The cost is that we cannot rotate the key without an
OTA itself; that's an acknowledged limitation, see
docs/THREAT_MODEL.md §A4 residual risk.

We deliberately do NOT support importing an external pubkey here —
the *generation* of the keypair is the trust event, and keeping it
in a single tool keeps the audit story simple. A future version may
add `--import-pubkey-only` for ceremonies where the private key
lives in an HSM.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
        Ed25519PrivateKey,
    )
except ImportError as exc:  # pragma: no cover
    sys.stderr.write(
        "error: the `cryptography` package is required.\n"
        "       pip install cryptography\n"
        f"       (import error: {exc})\n"
    )
    sys.exit(2)


# ── Path discovery ──────────────────────────────────────────────────

def _project_root_from(here: Path) -> Path:
    """Walk up from `here` until we find a directory containing both
    `main/` and `tools/sign/`. We use that as the project root so the
    script works whether you run it from the project root, from
    `tools/sign/`, or from a sibling directory."""
    for cand in [here, *here.parents]:
        if (cand / "main").is_dir() and (cand / "tools" / "sign").is_dir():
            return cand
    raise SystemExit(
        f"error: could not locate project root from {here} — "
        f"expected to find main/ + tools/sign/ at some ancestor."
    )


# ── Header writer ──────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
/*
 * ota_pubkey.h — ed25519 public key baked into the firmware image.
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerated by: tools/sign/generate_keys.py
 *
 * This file IS committed to the repo (the public key is, after all,
 * public). The matching private key lives in tools/sign/private.pem
 * which is .gitignore'd and chmod 600.
 *
 * Fingerprint (sha256(pubkey)[:8] in hex): {fingerprint}
 *
 * Generated on: {timestamp}
 */

#ifndef DASHBOARD_SECURE_OTA_PUBKEY_H
#define DASHBOARD_SECURE_OTA_PUBKEY_H

#include <stdint.h>

static const uint8_t ota_pubkey[32] = {{
{body}
}};

#endif /* DASHBOARD_SECURE_OTA_PUBKEY_H */
"""


def _format_pubkey_bytes(raw: bytes) -> str:
    """Format 32 bytes as 4 rows of 8 hex bytes, indented for the
    C array literal."""
    if len(raw) != 32:
        raise ValueError(f"pubkey must be 32 bytes, got {len(raw)}")
    rows = []
    for row_start in range(0, 32, 8):
        chunk = raw[row_start : row_start + 8]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    # Trim trailing comma on the very last byte for a marginally
    # cleaner literal (older C compilers warn; modern ones don't,
    # but it's free to be polite):
    rows[-1] = rows[-1].rstrip(",")
    return "\n".join(rows)


def _fingerprint(raw: bytes) -> str:
    import hashlib

    return hashlib.sha256(raw).hexdigest()[:16]


# ── Main ───────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_keys",
        description="Generate an ed25519 keypair for OTA signing.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Override the project root (default: auto-detect).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing private.pem / ota_pubkey.h.",
    )
    parser.add_argument(
        "--private-name",
        default="private.pem",
        help="Filename for the private key (default: private.pem).",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress informational output (still prints errors).",
    )
    args = parser.parse_args(argv)

    here = Path(__file__).resolve().parent
    root = args.out_dir.resolve() if args.out_dir else _project_root_from(here)

    private_path = root / "tools" / "sign" / args.private_name
    header_path = root / "main" / "secure" / "ota_pubkey.h"

    # Sanity: bail rather than clobber, unless --force.
    if private_path.exists() and not args.force:
        sys.stderr.write(
            f"error: {private_path} already exists. "
            f"Pass --force to overwrite (will invalidate every device "
            f"in the field running the matching pubkey).\n"
        )
        return 1

    # Generate.
    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()

    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_raw = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    assert len(public_raw) == 32, len(public_raw)

    # Write the private key with restrictive permissions.
    private_path.parent.mkdir(parents=True, exist_ok=True)
    private_path.write_bytes(private_pem)
    try:
        os.chmod(private_path, stat.S_IRUSR | stat.S_IWUSR)  # 0o600
    except (OSError, NotImplementedError):
        # Windows: chmod is largely advisory. We still set it; the
        # OS will ignore the group/other bits but accept the owner
        # read/write set. NTFS ACLs are the real control here; the
        # user should ensure the file is in a private profile dir.
        pass

    # Write the public key C header.
    import datetime

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_content = _HEADER_TEMPLATE.format(
        fingerprint=_fingerprint(public_raw),
        timestamp=datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        ),
        body=_format_pubkey_bytes(public_raw),
    )
    header_path.write_text(header_content, encoding="utf-8")

    # Quick self-check: can the C compiler `#include` this? We test
    # by checking the byte count of the literal in the rendered text.
    if header_content.count("0x") != 32:
        sys.stderr.write(
            f"internal error: header has {header_content.count('0x')} byte "
            f"literals, expected 32. Bailing without finalising.\n"
        )
        return 3

    if not args.quiet:
        print(f"wrote {private_path}  (chmod 600)")
        print(f"wrote {header_path}")
        print(f"pubkey fingerprint: {_fingerprint(public_raw)}")
        print()
        print("Next steps:")
        print(f"  - commit  {header_path.relative_to(root)} ")
        print(f"  - do NOT commit {private_path.relative_to(root)}")
        print(
            f"  - add to .gitignore if not already there:  "
            f"tools/sign/{args.private_name}"
        )

    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
