#!/usr/bin/env python3
"""
scaffold.py — generate a new esp32-agent-dashboard plugin from template.

Usage:
    python tools/sdk/scaffold.py my-plugin
    python tools/sdk/scaffold.py my-plugin --out ./plugins

What it creates under ./plugins/<name>/ :
    manifest.toml       — plugin identity, ABI, exports
    scene_<name>.c      — hello-world scene (single LVGL label + console verb)
    scene_<name>.h      — header for symmetry with main/scenes/
    CMakeLists.txt      — idf_component_register so `idf.py build` picks it up
    README.md           — what the plugin does + how to sign + how to add to firmware

Behaviour:
    - Idempotent on re-run. Files marked with `# AUTO-GENERATED` (TOML/CMake)
      or `/* AUTO-GENERATED */` (C) are rewritten; everything else is
      preserved (so a user's edits to scene_*.c survive a re-scaffold).
    - Refuses to overwrite if the target dir exists but has files not
      matching this template (so we don't blast over an unrelated dir).

Authoritative spec: docs/PLUGIN_SDK.md.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import textwrap
from pathlib import Path
from typing import Iterable


PLUGIN_ABI_VERSION = 1


# ----------------------------- templates ---------------------------------- #

MANIFEST_TEMPLATE = '''\
# AUTO-GENERATED by tools/sdk/scaffold.py — safe to edit; re-running
# scaffold.py rewrites this file. Hand-edit only if you also bump the
# AUTO-GENERATED marker off so the script leaves it alone.

[plugin]
name             = "{name}"
display_name     = "{display_name}"
version          = "0.1.0"
description      = "{description}"

[abi]
plugin_abi_version = {abi}
min_firmware       = "1.1.0"
max_firmware       = "<2.0.0"

[exports]
scenes           = ["scene_{name}"]
console_commands = ["plugin.{name}.hello"]

[signing]
# Replace with your real ed25519 key id once SEC1's tools/sign/ flow exists.
author_key_id    = "ed25519:plug-author-DEV"

[assets]
embed = []
'''


SCENE_C_TEMPLATE = '''\
/* SCAFFOLD-AUTOGEN: this file was generated by tools/sdk/scaffold.py.
 * Delete the next line to claim ownership; re-running scaffold.py
 * will then leave this file alone.
 *
 * AUTO-GENERATED
 *
 * Hello-world plugin scene for {display_name} ({name}).
 *
 * Demonstrates:
 *   • PLUGIN_SCENE_REGISTER macro
 *   • plugin_console_register at on_init
 *   • plugin_agent_state_borrow_const snapshot read
 *   • plugin_log convenience
 */

#include "scene_{name}.h"
#include "plugin_api.h"

#include <stdio.h>
#include <string.h>

#include "lvgl.h"

typedef struct {{
    lv_obj_t *label;
}} {name}_state_t;

static int cmd_hello(const plugin_console_args_t *args)
{{
    plugin_log("{name}", PLUGIN_LOG_INFO,
               "hello-verb fired (argc=%d)", args ? args->argc : 0);
    plugin_reply_ok("{name}", "hello from {name}");
    return 0;
}}

static void on_init(scene_t *s, lv_obj_t *parent)
{{
    {name}_state_t *st = lv_malloc_zeroed(sizeof(*st));
    s->user_data = st;

    st->label = lv_label_create(parent);
    lv_label_set_text(st->label, "{display_name}\\nplugin says hi");
    lv_obj_center(st->label);

    plugin_console_register("{name}", "hello", cmd_hello,
                            "{name} hello — sanity check");
}}

static void on_show(scene_t *s)
{{
    (void)s;
    plugin_log("{name}", PLUGIN_LOG_INFO, "shown");
}}

static void on_hide(scene_t *s)
{{
    (void)s;
}}

static int on_dash(scene_t *s, const char *verb,
                   const plugin_console_args_t *args)
{{
    (void)s; (void)args;
    plugin_log("{name}", PLUGIN_LOG_INFO,
               "dash verb received: %s", verb ? verb : "?");
    return 0;
}}

PLUGIN_SCENE_REGISTER(scene_{name},
    .id           = "{name}",
    .display_name = "{display_name}",
    .accent       = LV_COLOR_MAKE(0x4D, 0xA6, 0xFF),
    .description  = "{description}",
    .tags         = "plugin,scaffold",
    .init         = on_init,
    .on_show      = on_show,
    .on_hide      = on_hide,
    .on_dash      = on_dash);
'''


SCENE_H_TEMPLATE = '''\
/*
 * AUTO-GENERATED by tools/sdk/scaffold.py — header for scene_{name}.
 * Delete the AUTO-GENERATED line above to claim ownership.
 */

#pragma once

#include "harness/scene_framework.h"

#ifdef __cplusplus
extern "C" {{
#endif

extern scene_t scene_{name};

#ifdef __cplusplus
}}
#endif
'''


CMAKE_TEMPLATE = '''\
# AUTO-GENERATED by tools/sdk/scaffold.py
idf_component_register(
    SRCS
        "scene_{name}.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        lvgl__lvgl
        aurora-harness
    PRIV_REQUIRES
        # the dashboard's `main` component exposes plugin_api.h via its
        # INCLUDE_DIRS; depending on `main` keeps the plugin loosely
        # coupled to the firmware's plugin section symbols.
        main
)
'''


README_TEMPLATE = '''\
# {display_name} — esp32-agent-dashboard plugin

{description}

## Build

Drop this directory under your fork's `./components/` (or
`./plugins/{name}/`) and add it to `EXTRA_COMPONENT_DIRS` in your
`CMakeLists.txt`:

```cmake
list(APPEND EXTRA_COMPONENT_DIRS plugins)
```

Then `idf.py build` picks it up alongside the dashboard firmware.

## Sign

Before the firmware will accept the plugin at boot:

```
python tools/sdk/sign_plugin.py plugins/{name} --self-trust
```

This writes:

```
plugins/{name}/manifest.toml.sig.author
plugins/{name}/manifest.toml.sig.user
```

See `docs/PLUGIN_SDK.md` §5 for the threat model and the canonical
signing payload.

## Lifecycle

This template registers:

- a scene `scene_{name}` with `on_init`/`on_show`/`on_hide`/`on_dash`
- a single console verb `plugin.{name}.hello`

Iterate from there.

## Files

- `manifest.toml` — plugin identity and ABI declaration
- `scene_{name}.c` — your scene + console handlers
- `scene_{name}.h` — extern decl for the scene_t symbol
- `CMakeLists.txt` — ESP-IDF component manifest

Generated by `tools/sdk/scaffold.py` at ABI version {abi}.
'''


"""Markers that say "feel free to rewrite this file on re-scaffold".

We match these against the first few hundred bytes of the file. The
intent is that a user wanting to claim ownership of a scaffolded file
deletes the marker line and then re-runs scaffold.py without losing
their edits.

We deliberately use distinctive sentinel strings (not "AUTO" alone) so
prose mentioning "auto-generated" doesn't trigger false rewrites.
"""
AUTO_GEN_MARKERS = (
    "# AUTO-GENERATED by tools/sdk/scaffold.py",
    " * AUTO-GENERATED",
)


# ----------------------------- helpers ----------------------------------- #

def _is_valid_plugin_name(name: str) -> bool:
    return bool(re.match(r"^[a-z][a-z0-9_]{0,30}$", name))


def _normalise_name(raw: str) -> str:
    """Accept either `my-plugin` or `my_plugin`. Internally we use _."""
    return raw.replace("-", "_").lower()


def _display_name_from(name: str) -> str:
    parts = name.replace("_", " ").split()
    return " ".join(p.capitalize() for p in parts) if parts else name


def _file_is_auto_generated(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(512)
    except OSError:
        return False
    return any(m in head for m in AUTO_GEN_MARKERS)


def _safe_write(path: Path, content: str, *, force_rewrite: bool) -> str:
    """Write content if file doesn't exist OR file is AUTO-GENERATED.

    Returns one of "created", "rewrote", "kept", "refused".
    """
    if path.exists():
        if force_rewrite or _file_is_auto_generated(path):
            if path.read_text(encoding="utf-8", errors="replace") == content:
                return "kept"
            path.write_text(content, encoding="utf-8")
            return "rewrote"
        return "kept"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return "created"


def _unknown_files(target: Path, expected: Iterable[Path]) -> list[Path]:
    expected_set = {p.resolve() for p in expected}
    unknown: list[Path] = []
    if not target.exists():
        return unknown
    for child in target.iterdir():
        if child.is_dir():
            continue
        if child.resolve() not in expected_set:
            unknown.append(child)
    return unknown


# ----------------------------- main -------------------------------------- #

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="scaffold.py",
        description="Scaffold a new esp32-agent-dashboard plugin.",
    )
    parser.add_argument("name", help="plugin name (snake_case, [a-z0-9_])")
    parser.add_argument(
        "--out",
        default="./plugins",
        help="output parent directory (default: ./plugins)",
    )
    parser.add_argument(
        "--description",
        default="A scaffolded plugin — edit this in manifest.toml.",
        help="one-line description for manifest + README",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="rewrite ALL files even if not marked AUTO-GENERATED "
             "(refuses if target dir has unexpected sibling files)",
    )
    args = parser.parse_args(argv)

    name = _normalise_name(args.name)
    if not _is_valid_plugin_name(name):
        print(
            f"error: '{args.name}' → '{name}' is not a valid plugin name. "
            "Use snake_case, [a-z0-9_], 1-31 chars, starting with a letter.",
            file=sys.stderr,
        )
        return 2

    display_name = _display_name_from(name)
    target = Path(args.out).expanduser().resolve() / name

    context = dict(
        name=name,
        display_name=display_name,
        description=args.description,
        abi=PLUGIN_ABI_VERSION,
    )

    files = {
        target / "manifest.toml":      MANIFEST_TEMPLATE.format(**context),
        target / f"scene_{name}.c":    SCENE_C_TEMPLATE.format(**context),
        target / f"scene_{name}.h":    SCENE_H_TEMPLATE.format(**context),
        target / "CMakeLists.txt":     CMAKE_TEMPLATE.format(**context),
        target / "README.md":          README_TEMPLATE.format(**context),
    }

    # If target exists with files not in our template, refuse unless --force.
    if target.exists() and not args.force:
        unknown = _unknown_files(target, files.keys())
        if unknown:
            print(
                f"error: {target} exists and contains files not from this "
                "template — refusing to overwrite. Move them aside or pass "
                "--force.",
                file=sys.stderr,
            )
            for u in unknown:
                print(f"  unknown: {u.name}", file=sys.stderr)
            return 3

    for path, content in files.items():
        verdict = _safe_write(path, content, force_rewrite=args.force)
        rel = path.relative_to(target.parent)
        print(f"  {verdict:8s} {rel}")

    print()
    print(f"Plugin scaffolded under {target}")
    print(f"Next: edit scene_{name}.c, then `python tools/sdk/sign_plugin.py "
          f"{target} --self-trust`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
