/*
 * esp32_agent_dashboard_main.c — generated by `esp-harness new`.
 *
 * Wires up: NVS init -> display via BSP -> console protocol ->
 * default harness commands (?stat / scene / tap / swipe / ?dump) ->
 * scene framework -> one demo scene + per-frame fps tick.
 *
 * Replace scene_hello with your own scenes and add peripherals as needed.
 * See ../scenes/scene_hello.c for the smallest scene template.
 */

#include "esp_log.h"
#include "nvs_flash.h"

#include "lvgl.h"
#include "bsp/esp-bsp.h"

#include "harness/console_protocol.h"
#include "harness/scene_framework.h"
#include "harness/default_cmds.h"
#include "scenes/scenes.h"

static const char *TAG = "esp32_agent_dashboard";

static void frame_cb(lv_timer_t *t)
{
    (void)t;
    harness_record_frame();
}

static void on_scene_changed(int idx, const scene_t *current)
{
    /* App's UI chrome listens here. Replace with your own ui_shell sync
     * if you have one. For now just log. */
    if (current) {
        ESP_LOGI(TAG, "scene_changed idx=%d id=%s", idx, current->id);
    }
}

void app_main(void)
{
    /* NVS — needed if you use settings persistence, WiFi PHY cal, etc. */
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    /* Bring up display + LVGL via the BSP. */
    bsp_display_start();

    /* Console protocol + the default ?stat / scene / tap / swipe / ?dump set. */
    console_protocol_init();
    harness_default_register();

    /* Build the UI under the LVGL lock. */
    bsp_display_lock(-1);

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    scene_fw_init(scr);
    scene_fw_set_change_listener(on_scene_changed);
    scene_fw_register(&scene_hello);

    /* Per-frame tick feeds ?stat's fps field. */
    lv_timer_create(frame_cb, 33, NULL);

    bsp_display_unlock();

    ESP_LOGI(TAG, "ready, %d scene(s)", scene_fw_count());
}
